"""initial migration

Revision ID: 738885178785
Revises: None
Create Date: 2015-12-31 16:10:35.145966

"""

# revision identifiers, used by Alembic.
revision = '738885178785'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('agreement', sa.Float(), nullable=True),
    sa.Column('reputation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviewers_email'), 'reviewers', ['email'], unique=True)
    op.create_index(op.f('ix_reviewers_username'), 'reviewers', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviewers_username'), table_name='reviewers')
    op.drop_index(op.f('ix_reviewers_email'), table_name='reviewers')
    op.drop_table('reviewers')
    ### end Alembic commands ###
